pxsv2/pixelsaur2/pixelsaur2/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

#rutas de las funciones indicadas en cart.py para la pagina web
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

pxsv2/pixelsaur2/pixelsaur2/pixelsaur2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#directorio de rutas principales, cada uno engloba una funcionalidad importante del producto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('my_library/', include('my_library.urls', namespace='my_library')),
    path('', include('pixelsaurapp.urls', namespace='pixelsaurapp')), #tiene que cambiarse
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/urls.py
from django.urls import path
from . import views

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pixelsaurapp'

urlpatterns = [
    path('', views.product_list, name='product_list'), #nombre en el setings
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',  views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/regalo',  views.form_regalo, name='form_regalo'),
    path('busqueda', views.search_view, name='search_view'),
    path('pedir-dinero',views.pedir_dinero, name='pedir_dinero'),
    #path('<int:id>/<slug:slug>/', views.regalo_create, name='regalo_create'),
    #path('<str:slug>/', ItemsByCategoryView.as_view() , name='category-detail'),

    
]

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User  # Required to assign User as a borrower
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
from coupons.models import Coupon
from django import forms





# Create your models here.

#METODOS generales
    #meta: ordenacion de nombres a la hora de mostrarse en la web
    #get_absolute_url: ubicacion de acceso en la base de datos a pagina web
    
#tabla producto relacionado al DSV_10 del diagrama de clases,  cada uno de ellos pertenece a un atributo en orden.
class Product(models.Model):

    #category = models.ForeignKey('Category', related_name='products',on_delete=models.CASCADE)

    name = models.CharField(max_length=200,help_text="Entra el nombre de tu producto", db_index=True)
    category = TreeForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True)

    slug = models.SlugField(max_length=200)
    usuario = models.CharField(max_length=200,help_text="Entra el nombre del autor", db_index=True)
    #usuario_author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,blank=True)

    description = models.TextField(max_length=1000, help_text="Entra una descripcion del contenido")
    
    price = models.DecimalField(max_digits=10,decimal_places=2,default=99.99,null=True,blank=True)
    
    image = models.ImageField(null=True, blank=True,upload_to="contenidos/%Y/%m/%d") 
    archive = models.FileField(null=True, blank=True, upload_to="contenidos/%Y/%m/%d")
    available = models.BooleanField(default=True)
    
    created=models.DateField(auto_now_add=True,null=True,blank=True)
    updated=models.DateField(auto_now=True,null=True,blank=True)
    n_descarga = models.IntegerField(default=0 ,blank=True)
    val_promedio = models.FloatField(blank=True,default=0)
    pos_valoracion = models.IntegerField(blank=True,default=9999)
    pos_descarga = models.IntegerField(default=9999,blank=True)

    def promedio(self,valor):
        self.val_promedio = (self.val_promedio +valor)/2
    #define las posiciones respecto a las anteriores, de valoracion y de descargas
    def get_posv(self):
        return self.pos_valoracion
    def get_calificaion(self):
        return self.val_promedio
    def set_posv(self, valor):
        self.pos_valoracion = valor
    def get_posd(self):
        return self.n_descarga
    def set_posd(self, valor):
        self.pos_descarga = valor
    #cada ves que descarga, suma en uno al n de descargas del producto
    def ondescarga(self):
        self.n_descarga = self.n_descarga +1
        self.save()
    
   
    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name
   
    #url para redirigir a la pagina especifica
    def get_absolute_url(self):
        return reverse('pixelsaurapp:product_detail', args=[self.id, self.slug])
    
    #url que redirecciona
    def get_downloadable_url(self):   
        return reverse('my_library:my_product_detail', args=[self.id, self.slug])
    #obtiene el link especifico del archivo, para las descargas
    def get_link(self):
        return '../../media/'+self.archive.name
    def save(self, *args, **kwargs):
      if not self.slug:
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
      super().save(*args, **kwargs)



#tabla categoria perteneciente al DSV_12 los id, son automaticos, los nombres.
class Category(MPTTModel):
    name = models.CharField(max_length=100, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = models.SlugField(max_length=100, null=True, blank=True)
    #carga de libreria para poder mostrar la categoria en el administrador
    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    #sobrecarga de la funcion save, que guarda los productos que nosotros deseamos
    def save(self, *args, **kwargs):
        value = self.name
        if not self.slug:
            self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)
    #funcion para obtener todos los hijos y poderlos filtrar en cada producto    
    def get_childrens(self):
        return Category.objects.filter(parent=self).all()

    #redireccion para cargar los contenidos pertenecientes a una categoria    
    def get_absolute_url(self):
        return reverse('pixelsaurapp:product_list_by_category', args=[self.slug])    



#tabla calificacion, que se redirigira a las otras tablas, la calificacion numerica y la fecha por producto
class Calificacion(models.Model):
    product = models.ForeignKey(Product,related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='reviews',on_delete=models.CASCADE,null=True)
    rating = models.FloatField(default=3.0)
    date_rating = models.DateField(auto_now_add=True, null=True)
 
#tabla de regalo, podra ser accesada por el que envia y por el que recibe
#el que envia guarda la information en la tabla
#el que recibe busca su id y muestra los contenidos referentes a su id
class Regalo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True,blank=True)
    desc_cod = models.CharField(max_length=50,unique=True, null=True, blank=True)
    user_send = models.ForeignKey( User, null=True, blank=True, on_delete=models.CASCADE)
    user_rece = models.EmailField( null=True, blank=True)
    dedicatoria = models.TextField(null=True, blank=True, max_length=200)
    #funcion del que recibe, los mensajes que le pertenecen
    def get_mensajes(self,email):
        print(self.objects.all().filter(user_rece=email))
        return self.objects.all().filter(user_rece=email)

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/forms.py
from django import forms
from .models import Regalo
#formulario de creacion de regalo
class RegaloCreateForm(forms.ModelForm):
    class Meta: 
        model =Regalo        
        fields = ['user_rece','dedicatoria']
class ViewForm(forms.Form):
    order = forms.CharField(max_length=40)
    
#formulario busqueda
class BusquedaForm(forms.Form):
    busqueda = forms.CharField(max_length=40)

#formulario para ingresar la cantidad de dinero deseada
class PedirDineroForm(forms.Form):
    cantidad = forms.FloatField()

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, Regalo
from cart.forms import CartAddProductForm

from .forms import RegaloCreateForm, ViewForm, BusquedaForm, PedirDineroForm
from account.models import Wallet
from coupons.models import Coupon
from datetime import datetime, date, timedelta
#for Login
from django.contrib.auth.decorators import login_required
from account.models import Wallet
#from .forms import LoginForm

#muestra una lista de productos por categoria
@login_required
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    regalo = Regalo(request)
    regalo = Regalo.objects.all().filter(user_rece=request.user.email)
    #condicional de categoria
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category__id__in=[c.id for c in category.get_childrens()]+[category.id])
    #print(category.get_childrens())
    forma = ViewForm()
    slides = products[:10]
    if request.method == 'POST':
        forma = ViewForm(request.POST)
        #el formulario tendra tres tipos de ordenamiento, por novedad, por calificaion, por numero de descargas
        if forma.is_valid():
            control = forma.cleaned_data.get("order")
            if control == "Nuevo": 
                products = products.order_by('created')
            elif control == "Mejor Valorados":
                products = products.order_by('val_promedio')
                #toma los 10 primeros y los manda como variables al slideshow
                slides = products[:10]
                
                cambio = []
                i = 1
                for slide in slides:
                    cambio.append(slide.get_posv() - i) 
                    slide.set_posv(i) 
                    i = i+1
                
                return render(request, 'pixelsaurapp/product/list.html', {'category': category, 'categories': categories,'cambio':cambio,'slides':slides ,'products': products, 'section': 'product_listLogin', 'regalo': regalo })
            elif control == "Mas Descargados":
                products = products.order_by('n_descarga')
                slides = products[:10]
                cambio = []
                i=1
                #toma el i para definir que cambio tuvo frente a la anterior actualizacion
                for slide in slides:
                    cambio.append(slide.get_posd() - i) 
                    slide.set_posd(i) 
                    i = i+1 
                return render(request, 'pixelsaurapp/product/list.html', {'category': category, 'categories': categories,'cambio':cambio,'slides':slides ,'products': products, 'section': 'product_listLogin', 'regalo': regalo})
    # al final muestra las variables creadas para su uso
    return render(request, 'pixelsaurapp/product/list.html',
        {'category': category, 'categories': categories, 'products': products, 'section': 'product_listLogin', 'regalo': regalo, 'slides': slides})

#funcion que usa el formulario de pedir dinero para insertarlo en la tabla de admin
def pedir_dinero(request):
    categories = Category.objects.all()
    form = PedirDineroForm()
    dinero = Wallet.objects.values('money').filter(user_id = request.user.id)
    dinero = dinero[0]['money']
    if request.method == 'POST':
        form = PedirDineroForm(request.POST)
        if form.is_valid():
            print('in buscar form')
            cantidad = form.cleaned_data['cantidad']
            #print(type(cantidad))
            #Wallet.objects.create(peticion = cantidad)
            Wallet.objects.filter(user_id = request.user.id).update(peticion = cantidad)

    return render(request, 'pixelsaurapp/balance/balancemain.html',{'categories': categories,'form':form,'dinero':dinero})



#vista que toma el formulario de busqueda para hcer un filter en los productos, tambien muestra las categorias como productos en si
def search_view(request, category_slug = None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    #condicional de categoria
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category__id__in=[c.id for c in category.get_childrens()]+[category.id])
    form = BusquedaForm()
    if request.method == 'POST':
        form = BusquedaForm(request.POST)
        if form.is_valid():
            products =  products.filter(name__contains = form.cleaned_data['busqueda'])
            return render(request, 'pixelsaurapp/busqueda/res_busqueda.html',
                {'category': category, 'categories': categories, 'products': products, 'section': 'product_listLogin'})

    return render(request, 'pixelsaurapp/busqueda/buscarlist.html',
        {'category': category, 'categories': categories, 'products': products, 'section': 'product_listLogin'})
    

#muestra el detalle del producto cuando se le hace click
def product_detail(request, slug, id):
    product = get_object_or_404(Product,
                                id = id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    categories = Category.objects.all()
    califi = Product.objects.filter(id = id).values('val_promedio')

    print(califi)
    return render(request,
                  'pixelsaurapp/product/detail.html',
                  {'product': product,
                    'slug':slug,'id':id,
                    'califi':califi,
                  'categories': categories,
                   'cart_product_form': cart_product_form})


#vista que une el formulario de regalo para que puedas ingresar el mensaje del regalo y el usuario, previamente seleccionaste el producto y validaste que tienes dinero suficiente
def form_regalo(request,slug,id):
    wallett = Wallet(request)
    product = get_object_or_404(Product,id =id,slug=slug)
    categories = Category.objects.all()
    dinero = Wallet.objects.values('money').filter(user_id = request.user.id)
    dinero = dinero[0]['money']
   
    cod_desc = str(id)+slug
    #cod_desc = Product.objects.values('id')+Product.objects.values('slug')
    if request.method == 'POST':
        
        
        if product.price <= dinero:
            form = RegaloCreateForm(request.POST)
           
            if form.is_valid():
                #resta el dinero
                Wallet.objects.filter(user_id = request.user.id).update(money = dinero - product.price)
                #crea el cupon de descuento
                Coupon.objects.create(code = cod_desc, valid_from = str(datetime.now()), valid_to = str(datetime.now() + timedelta(days=3)), discount = 100, active= True)
                #lo guarda en la tabla de regalos
                Regalo.objects.create(product=product,desc_cod=cod_desc,user_send = request.user , user_rece = form.cleaned_data['user_rece'], dedicatoria = form.cleaned_data['dedicatoria'])
                
            return render(request, 'pixelsaurapp/regalo/regalocreado.html', {'categories':categories,'slug':slug,'id':id})
        else:
            print('no suficiente dinero')
            form  = RegaloCreateForm()
    else:
        print('elseif')
        form = RegaloCreateForm()
    return  render(request, 'pixelsaurapp/regalo/regalocrearform.html', { 'categories':categories,'form': form,'slug':slug,'id':id})

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/templates/pixelsaurapp/product/detail.html
{% extends "pixelsaurapp/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail" style="margin-left: 50px">
    <h2>    <a href="{{ product.category.get_absolute_url }}">
      {{ product.category }}
    </a></h2>

    <div>     <img src="{% if product.image %}{{ product.image.url }}{% else %}
      {% static "img/no_image.png" %}{% endif %}"> </div>
    <div>
      <h1>{{ product.name }}</h1>
      <p class="price">${{ product.price }}</p>
    </div>
    <!-- por ahora -->
    
    <label class="rating-label"><strong>Rating: </strong>
    <br><br><br><br>
      <input
      class="rating rating--nojs"
      max="5"
      step="0.0005"
      type="range"
      name = "rating"
      value="{{califi}}"readonly>
    </label>
    <br><br><br><br><br>
    
    <form style = "float:bottom" action="{% url "cart:cart_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>

    <p class = "text-right">
      <a href ="{% url "pixelsaurapp:form_regalo" product.id product.slug %}" class="button">
        Comprar como regalo
      </a>
    </p>

    <!--
      <form method="post" action="{% url "enviar a un formulario directo de formulario regalo

    -->
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/templates/pixelsaurapp/product/list.html
{% extends "pixelsaurapp/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  
  
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <div class = "slideshows">
      <div class="slideshow-container">

        <!-- Full-width images with number and caption text -->
        
        <div class="mySlides fade">
          <div class="numbertext">1 / 10</div>
          <img src="{% if slides.0.image %}{{ slides.0.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">          <div class="text"> + {{ cambio.0 }}</div>
          <a href="{{ slides.0.get_absolute_url }}">Compra ahora</a>
        </div>
      
        <div class="mySlides fade">
          <div class="numbertext">2 / 10</div>
          <img src="{% if slides.1.image %}{{ slides.1.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">          <div class="text"> - {{ cambio.2 }}</div>
          <a href="{{ slides.1.get_absolute_url }}">Compra ahora</a>
        </div>
        <div class="mySlides fade">
          <div class="numbertext">3 / 10</div>
          <img src="{% if slides.2.image %}{{ slides.2.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">          <div class="text"> +{{ cambio.3 }}</div>
          <a href="{{ slides.2.get_absolute_url }}">Compra ahora</a>
        </div>
        <div class="mySlides fade">
          <div class="numbertext">4 / 10</div>
          <img src="{% if slides.3.image %}{{ slides.3.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">          <div class="text"> - {{ cambio.4 }}</div>
          <a href="{{ slides.3.get_absolute_url }}">Compra ahora</a>
        </div>

      
    
        
        <!-- Next and previous buttons -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <br>
      
      <!-- The dots/circles -->
      <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
        <span class="dot" onclick="currentSlide(4)"></span>
      </div>

      <script>
        let slideIndex = 1;
        showSlides(slideIndex);
        
        function plusSlides(n) {
          showSlides(slideIndex += n);
        }
        
        function currentSlide(n) {
          showSlides(slideIndex = n);
        }
        
        function showSlides(n) {
          let i;
          let slides = document.getElementsByClassName("mySlides");
          let dots = document.getElementsByClassName("dot");
          if (n > slides.length) {slideIndex = 1}    
          if (n < 1) {slideIndex = slides.length}
          for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";  
          }
          for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
          }
          slides[slideIndex-1].style.display = "block";  
          dots[slideIndex-1].className += " active";
        }
        </script>
      
      <form method="POST" class = "eligelistas"  >
        {% csrf_token %}
        <input type="radio" name="order" id="rating1" value="Nuevo" required /><label for="rating1" title="0.5" class="half">Nuevo</label>
        <input type="radio" name="order" id="rating2" value="Mejor Valorados" required /><label for="rating2" title="1">Mejor Valorados</label>
        <input type="radio" name="order" id="rating3" value="Mas Descargados" required /><label for="rating3" title="1.5" class="half">Mas Descargados</label>
        <input type="submit" value = "Actualizar" >
      </form>
    </div>
    <div class="lista-prductos">
      {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.price }}
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}