pxsv2/pixelsaur2/pixelsaur2/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

#rutas de las funciones indicadas en cart.py para la pagina web
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

pxsv2/pixelsaur2/pixelsaur2/coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

pxsv2/pixelsaur2/pixelsaur2/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

pxsv2/pixelsaur2/pixelsaur2/pixelsaur2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#directorio de rutas principales, cada uno engloba una funcionalidad importante del producto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('my_library/', include('my_library.urls', namespace='my_library')),
    path('', include('pixelsaurapp.urls', namespace='pixelsaurapp')), #tiene que cambiarse
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pxsv2/pixelsaur2/pixelsaur2/pixelsaurapp/urls.py
from django.urls import path
from . import views

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pixelsaurapp'

urlpatterns = [
    path('', views.product_list, name='product_list'), #nombre en el setings
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',  views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/regalo',  views.form_regalo, name='form_regalo'),
    path('busqueda', views.search_view, name='search_view'),
    path('pedir-dinero',views.pedir_dinero, name='pedir_dinero'),
    #path('<int:id>/<slug:slug>/', views.regalo_create, name='regalo_create'),
    #path('<str:slug>/', ItemsByCategoryView.as_view() , name='category-detail'),

    
]

pxsv2/pixelsaur2/pixelsaur2/cart/models.py
from django.db import models

# Create your models here.

pxsv2/pixelsaur2/pixelsaur2/cart/forms.py
from django import forms
#funcion adicional para limitar la cantidad de compras de un producto
#extension extra en caso de que se pueda comprar para mas cantidad de un producto
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 2)]


#formulario para sumar al carrito despues de navegar en la vista de productos lista
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

pxsv2/pixelsaur2/pixelsaur2/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from pixelsaurapp.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


#require_POST es necesario ya que estas funciones se validan despues de enviar el formulario

#Funcion para agregar productos al carro, verificar el formulario y existencia de producto
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

#FUncion para eliminar productos del carrito
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

#FUncion para mostrar el precio de detalle despues de agregacion de descuento
def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={ 'quantity': item['quantity'], 'override': True})
    
    coupon_apply_form = CouponApplyForm()


    return render(request, 'cart/detail.html', {'cart': cart,'categories':categories, 'coupon_apply_form': coupon_apply_form})

pxsv2/pixelsaur2/pixelsaur2/cart/templates/cart/detail.html
{% extends "pixelsaurapp/base.html" %}
{% load static %}

{% block title %}
Your shopping cart
{% endblock %}
{% block content %}

<!--Header arriba derecha de la imagen del carrito-->


<!--Tabla de descripcion unitaria de elementos en el carrito-->
<div class="tablaform">

    <table class="cart">
      <thead>
        <tr>
          <th>Image</th>
          <th>Product</th>
          <th>Remove</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>

    <!--recorrido para mostrar imagenes y precio-->
        {% for item in cart %}
          {% with product=item.product %}
            <tr>
              <td>
                <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }}
                  {% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
              </td>
              <td>{{ product.name }}</td>
              <td>
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                  <input type="submit" value="Remove">
                  {% csrf_token %}
                </form>
              </td>
              <td class="num">${{ item.total_price }}</td>
            </tr>
          {% endwith %}
        {% endfor %}
      {% if cart.coupon %}
      <tr class="subtotal">
        <td>Subtotal</td>
        <td colspan="2"></td>
        <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>
          "{{ cart.coupon.code }}" coupon
          ({{ cart.coupon.discount }}% off)
        </td>
        <td colspan="2"></td>
        <td class="num neg">
          - ${{ cart.get_discount|floatformat:2 }}
        </td>
      </tr>
      {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="2"></td>
        <td class="num">
          ${{ cart.get_specific_discount|floatformat:2 }}
        </td>
      </tr>
      </tbody>
    </table>
    <div id="couponform" class="row">
      <div class="column">
        <p>Apply a coupon:</p>
        <form action="{% url "coupons:apply" %}" method="post">
          {{ coupon_apply_form }}
          <input type="submit" value="Apply">
          {% csrf_token %}
        </form>
      </div>
      <div class="column">
        
      </div>
    </div>
  </div>  

  <p class="text-right">
    <a href="{% url "pixelsaurapp:product_list" %}" class="button
      light">Continue shopping</a>
    <a href="{% url "orders:order_create" %}" class="button">
      Checkout
    </a>
  </p>
 
{% endblock %}